import { CharacterClass, EquipmentItem, SkillUpgrade, TalentNode, BestiaryEntry } from './types';

export const HERO_CLASSES: Record<string, CharacterClass> = {
  warrior: {
    id: 'warrior',
    name: 'Caballero de Hierro',
    title: 'Defensor del Bastión',
    description: 'Guerrero blindado con tremenda resistencia y espadazos cortantes. Ideal para combate cuerpo a cuerpo.',
    baseHp: 160,
    baseDamage: 22,
    baseSpeed: 3.4,
    baseDefense: 6,
    baseCritRate: 0.08,
    baseCritDamage: 1.5,
    baseRegen: 0.5,
    startingSkillId: 'spinning_blades',
    color: '#3b82f6',
    iconName: 'Shield',
  },
  mage: {
    id: 'mage',
    name: 'Maga del Vacío',
    title: 'Señora de los Arcanos',
    description: 'Canaliza proyectiles arcanos y magia de hielo. Gran daño destructivo a distancia a cambio de menor vitalidad.',
    baseHp: 105,
    baseDamage: 32,
    baseSpeed: 3.6,
    baseDefense: 1,
    baseCritRate: 0.12,
    baseCritDamage: 1.7,
    baseRegen: 0.2,
    startingSkillId: 'arcane_missile',
    color: '#a855f7',
    iconName: 'Sparkles',
  },
  rogue: {
    id: 'rogue',
    name: 'Pícaro Sombrío',
    title: 'Asesino de las Sombras',
    description: 'Veloz como el viento, letales ataques críticos y evasión sublime. Lanza kunais venenosos.',
    baseHp: 120,
    baseDamage: 26,
    baseSpeed: 4.1,
    baseDefense: 3,
    baseCritRate: 0.22,
    baseCritDamage: 2.0,
    baseRegen: 0.3,
    startingSkillId: 'poison_kunai',
    color: '#10b981',
    iconName: 'Zap',
  },
};

export const SKILL_POOL: SkillUpgrade[] = [
  // Active Skills
  {
    id: 'spinning_blades',
    name: 'Hojas Espectrales',
    description: 'Hojas arcanas giran continuamente alrededor de ti, cortando a los enemigos cercanos.',
    type: 'active',
    maxLevel: 5,
    icon: 'RotateCw',
    color: '#60a5fa',
    rarity: 'rare',
  },
  {
    id: 'frost_nova',
    name: 'Nova Glacial',
    description: 'Emite periódicamente una onda de escarcha que congela y ralentiza a las hordas enemigas.',
    type: 'active',
    maxLevel: 5,
    icon: 'Snowflake',
    color: '#38bdf8',
    rarity: 'rare',
  },
  {
    id: 'chain_lightning',
    name: 'Rayo Eléctrico',
    description: 'Lanza una descarga que salta entre varios enemigos cercanos infligiendo daño electrizante.',
    type: 'active',
    maxLevel: 5,
    icon: 'Zap',
    color: '#fbbf24',
    rarity: 'epic',
  },
  {
    id: 'arcane_missile',
    name: 'Orbe Arcano',
    description: 'Dispara proyectiles mágicos perseguidores automáticos hacia los monstruos más amenazantes.',
    type: 'active',
    maxLevel: 5,
    icon: 'Flame',
    color: '#f43f5e',
    rarity: 'common',
  },
  {
    id: 'holy_aura',
    name: 'Aura Radiante',
    description: 'Un círculo consagrado que quema a los demonios y no-muertos que se atrevan a acercarse.',
    type: 'active',
    maxLevel: 5,
    icon: 'Sun',
    color: '#eab308',
    rarity: 'rare',
  },
  {
    id: 'poison_kunai',
    name: 'Dagas Venenosas',
    description: 'Lanza abanicos de dagas rápidas que dejan toxinas letales infligiendo daño por segundo.',
    type: 'active',
    maxLevel: 5,
    icon: 'Target',
    color: '#34d399',
    rarity: 'common',
  },
  // Passive Boosts
  {
    id: 'might_boost',
    name: 'Fuerza Titánica',
    description: '+20% Daño a todos los ataques y habilidades.',
    type: 'passive',
    maxLevel: 5,
    icon: 'Swords',
    color: '#ef4444',
    rarity: 'common',
  },
  {
    id: 'vitality_boost',
    name: 'Corazón de Hierro',
    description: '+25% Vida Máxima y restaura de inmediato 30 puntos de vida.',
    type: 'passive',
    maxLevel: 5,
    icon: 'Heart',
    color: '#ec4899',
    rarity: 'common',
  },
  {
    id: 'swift_boots',
    name: 'Pies de Pluma',
    description: '+15% Velocidad de movimiento y mayor fluidez de esquiva.',
    type: 'passive',
    maxLevel: 5,
    icon: 'Wind',
    color: '#06b6d4',
    rarity: 'common',
  },
  {
    id: 'vampire_fangs',
    name: 'Colmillos Vampíricos',
    description: 'Restaura un 3% de vida al derrotar enemigos con tus golpes.',
    type: 'passive',
    maxLevel: 5,
    icon: 'Droplet',
    color: '#dc2626',
    rarity: 'epic',
  },
  {
    id: 'critical_eye',
    name: 'Ojo del Verdugo',
    description: '+12% Probabilidad de Golpe Crítico y +30% Daño Crítico.',
    type: 'passive',
    maxLevel: 5,
    icon: 'Crosshair',
    color: '#f59e0b',
    rarity: 'rare',
  },
  {
    id: 'magnetic_pull',
    name: 'Imán de Almas',
    description: '+60% Radio de atracción de gemas de experiencia y monedas de oro.',
    type: 'passive',
    maxLevel: 5,
    icon: 'Magnet',
    color: '#8b5cf6',
    rarity: 'common',
  },
  {
    id: 'stone_skin',
    name: 'Piel de Piedra',
    description: 'Reduce todo el daño recibido en 4 puntos directos y gana +15% de armadura.',
    type: 'passive',
    maxLevel: 5,
    icon: 'ShieldAlert',
    color: '#78716c',
    rarity: 'rare',
  },
];

export const TALENTS_CONFIG: TalentNode[] = [
  {
    id: 'might',
    name: 'Fuerza Ancestral',
    description: 'Aumenta el daño infligido de todas tus armas y hechizos.',
    icon: 'Flame',
    maxLevel: 10,
    costPerLevel: 120,
    soulCostPerLevel: 0,
    statBonusPerLevel: 0.08, // +8%
    unit: '%',
    statKey: 'damageMultiplier',
  },
  {
    id: 'vitality',
    name: 'Vitalidad Eterna',
    description: 'Aumenta la vida máxima permanente del héroe.',
    icon: 'Heart',
    maxLevel: 10,
    costPerLevel: 100,
    soulCostPerLevel: 0,
    statBonusPerLevel: 20, // +20 HP
    unit: ' HP',
    statKey: 'maxHp',
  },
  {
    id: 'defense',
    name: 'Placas Forjadas',
    description: 'Reduce el daño directo recibido de los golpes enemigos.',
    icon: 'Shield',
    maxLevel: 8,
    costPerLevel: 150,
    soulCostPerLevel: 1,
    statBonusPerLevel: 2, // +2 armor
    unit: ' DEF',
    statKey: 'defense',
  },
  {
    id: 'agility',
    name: 'Agilidad Felina',
    description: 'Aumenta la velocidad de desplazamiento por la mazmorra.',
    icon: 'Wind',
    maxLevel: 6,
    costPerLevel: 180,
    soulCostPerLevel: 1,
    statBonusPerLevel: 0.15,
    unit: ' Vel',
    statKey: 'moveSpeed',
  },
  {
    id: 'lethality',
    name: 'Instinto Asesino',
    description: 'Mayor probabilidad de asestar golpes críticos devastadores.',
    icon: 'Crosshair',
    maxLevel: 8,
    costPerLevel: 220,
    soulCostPerLevel: 2,
    statBonusPerLevel: 0.04, // +4% crit
    unit: '%',
    statKey: 'critRate',
  },
  {
    id: 'regen',
    name: 'Fuente de Vida',
    description: 'Regeneración pasiva de vida cada segundo en combate.',
    icon: 'Activity',
    maxLevel: 5,
    costPerLevel: 250,
    soulCostPerLevel: 2,
    statBonusPerLevel: 0.6,
    unit: ' HP/s',
    statKey: 'healthRegen',
  },
  {
    id: 'magnet',
    name: 'Magnetismo Arcano',
    description: 'Atrae gemas de experiencia y oro desde mayor distancia.',
    icon: 'Radio',
    maxLevel: 6,
    costPerLevel: 140,
    soulCostPerLevel: 0,
    statBonusPerLevel: 25,
    unit: ' px',
    statKey: 'pickupRadius',
  },
  {
    id: 'greed',
    name: 'Fortuna del Saqueador',
    description: 'Aumenta la cantidad de oro obtenida de cofres y monstruos.',
    icon: 'Coins',
    maxLevel: 8,
    costPerLevel: 160,
    soulCostPerLevel: 1,
    statBonusPerLevel: 0.12, // +12%
    unit: '%',
    statKey: 'goldMultiplier',
  },
];

export const INITIAL_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'sword_starter',
    name: 'Espada de Acero Viejo',
    slot: 'weapon',
    rarity: 'common',
    level: 1,
    maxLevel: 10,
    statType: 'damage',
    statValue: 8,
    bonusText: '+8 Daño Base',
    icon: 'Sword',
    upgradeCostGold: 80,
  },
  {
    id: 'armor_starter',
    name: 'Cota de Cuero Reforzado',
    slot: 'armor',
    rarity: 'common',
    level: 1,
    maxLevel: 10,
    statType: 'defense',
    statValue: 4,
    bonusText: '+4 Armadura & +20 HP',
    icon: 'Shield',
    upgradeCostGold: 70,
  },
  {
    id: 'ring_starter',
    name: 'Anillo de Amatista',
    slot: 'relic',
    rarity: 'common',
    level: 1,
    maxLevel: 10,
    statType: 'crit',
    statValue: 0.05,
    bonusText: '+5% Probabilidad Crítica',
    icon: 'Sparkles',
    upgradeCostGold: 90,
  },
  {
    id: 'boots_starter',
    name: 'Botas de Explorador',
    slot: 'boots',
    rarity: 'common',
    level: 1,
    maxLevel: 10,
    statType: 'speed',
    statValue: 0.3,
    bonusText: '+0.3 Velocidad Movimiento',
    icon: 'Footprints',
    upgradeCostGold: 75,
  },
];

export const LOOTABLE_EQUIPMENT_POOL: EquipmentItem[] = [
  {
    id: 'blade_shadow',
    name: 'Filo de la Vorágine',
    slot: 'weapon',
    rarity: 'rare',
    level: 1,
    maxLevel: 15,
    statType: 'damage',
    statValue: 18,
    bonusText: '+18 Daño y +8% Crítico',
    icon: 'Sword',
    upgradeCostGold: 160,
  },
  {
    id: 'staff_archmage',
    name: 'Cetro de la Estrella Fugaz',
    slot: 'weapon',
    rarity: 'epic',
    level: 1,
    maxLevel: 20,
    statType: 'damage',
    statValue: 28,
    bonusText: '+28 Daño y proyectiles explosivos',
    icon: 'Wand2',
    upgradeCostGold: 300,
  },
  {
    id: 'chest_demon',
    name: 'Coraza del Coloso Carmesí',
    slot: 'armor',
    rarity: 'epic',
    level: 1,
    maxLevel: 20,
    statType: 'hp',
    statValue: 90,
    bonusText: '+90 HP y +8 Armadura',
    icon: 'ShieldAlert',
    upgradeCostGold: 280,
  },
  {
    id: 'amulet_immortal',
    name: 'Reliquia del Fénix Eterno',
    slot: 'relic',
    rarity: 'legendary',
    level: 1,
    maxLevel: 25,
    statType: 'hp',
    statValue: 120,
    bonusText: '+120 HP y revive una vez con 40% vida',
    icon: 'Flame',
    upgradeCostGold: 600,
  },
  {
    id: 'boots_hermes',
    name: 'Grebas de Mercurio',
    slot: 'boots',
    rarity: 'rare',
    level: 1,
    maxLevel: 15,
    statType: 'speed',
    statValue: 0.6,
    bonusText: '+0.6 Velocidad y esquiva',
    icon: 'Footprints',
    upgradeCostGold: 180,
  },
];

export const BESTIARY_CATALOG: BestiaryEntry[] = [
  {
    type: 'skeleton',
    name: 'Esqueleto Guardián',
    description: 'Guerrero no-muerto reanimado con una espada oxidada. Persigue tenazmente a cualquier intruso en la catacumba.',
    kills: 0,
    icon: 'Skull',
  },
  {
    type: 'bat',
    name: 'Murciélago Abisal',
    description: 'Criatura rápida que ataca en enjambres desde las sombras del techo. Fácil de eliminar pero ágil.',
    kills: 0,
    icon: 'Feather',
  },
  {
    type: 'goblin_archer',
    name: 'Tirador Sombrío',
    description: 'Arquero taimado que dispara flechas venenosas desde la distancia mientras huye del héroe.',
    kills: 0,
    icon: 'Crosshair',
  },
  {
    type: 'necromancer',
    name: 'Cultista del Velo',
    description: 'Mago oscuro que lanza calaveras espectrales malditas y drena el alma de sus víctimas.',
    kills: 0,
    icon: 'Ghost',
  },
  {
    type: 'minotaur',
    name: 'Minotauro Acorazado',
    description: 'Bestia colosal que brama y embiste a gran velocidad cuando detecta al jugador en línea recta.',
    kills: 0,
    icon: 'ShieldAlert',
  },
  {
    type: 'demon_boss',
    name: 'Belial, Señor del Abismo',
    description: 'Monstruo titánico de magma y azufre que custodia las profundidades. Desata lluvias de fuego infernal.',
    kills: 0,
    icon: 'Crown',
  },
];
